import { useState, useEffect } from 'react'
import {
  X, Mail, Paperclip, BarChart2, TableProperties,
  Send, Check, FileText,
} from 'lucide-react'
import type { ChartConfig, DataSource, SubSheetData } from '../types'

interface Attachment {
  id: string
  label: string
  sublabel: string
  kind: 'chart' | 'table' | 'csv' | 'pivot'
  checked: boolean
}

interface EmailModalProps {
  isOpen: boolean
  onClose: () => void
  charts: ChartConfig[]
  dataSource: DataSource | null
  userEmail: string
  reportName: string
}

function buildAttachments(
  charts: ChartConfig[],
  dataSource: DataSource | null,
): Attachment[] {
  const items: Attachment[] = []

  charts.forEach(c => {
    if (c.type === 'table') {
      items.push({
        id: c.id,
        label: c.title,
        sublabel: 'Data table — embedded inline in email',
        kind: 'table',
        checked: true,
      })
    } else {
      items.push({
        id: c.id,
        label: c.title,
        sublabel: `Chart image (${c.type}) — attached as PNG`,
        kind: 'chart',
        checked: true,
      })
    }
  })

  // Sub-sheets (pivot tables etc.)
  if (dataSource?.subSheets && dataSource.subSheets.length > 0) {
    dataSource.subSheets.forEach(s => {
      items.push({
        id: `sub_${s.name}`,
        label: s.name,
        sublabel: `${s.data.length} rows — attached as table`,
        kind: 'pivot',
        checked: s.kind === 'report' || s.kind === 'summary',
      })
    })
  }

  // Raw CSV
  if (dataSource && dataSource.data.length > 0) {
    items.push({
      id: 'raw_csv',
      label: `${dataSource.name} — Raw Data`,
      sublabel: `${dataSource.data.length} rows · ${dataSource.columns.length} columns — CSV file`,
      kind: 'csv',
      checked: false,
    })
  }

  return items
}

const kindMeta: Record<
  Attachment['kind'],
  { icon: React.ReactNode; badge: string; badgeClass: string; iconClass: string }
> = {
  chart: {
    icon: <BarChart2 size={14} />,
    badge: 'IMAGE',
    badgeClass: 'bg-indigo-50 text-indigo-600',
    iconClass: 'bg-indigo-100 text-indigo-600',
  },
  table: {
    icon: <TableProperties size={14} />,
    badge: 'TABLE',
    badgeClass: 'bg-slate-100 text-slate-600',
    iconClass: 'bg-slate-100 text-slate-600',
  },
  pivot: {
    icon: <TableProperties size={14} />,
    badge: 'PIVOT',
    badgeClass: 'bg-purple-50 text-purple-600',
    iconClass: 'bg-purple-100 text-purple-600',
  },
  csv: {
    icon: <FileText size={14} />,
    badge: 'CSV',
    badgeClass: 'bg-emerald-50 text-emerald-600',
    iconClass: 'bg-emerald-100 text-emerald-600',
  },
}

export default function EmailModal({
  isOpen,
  onClose,
  charts,
  dataSource,
  userEmail,
  reportName,
}: EmailModalProps) {
  const [subject, setSubject] = useState('')
  const [body, setBody] = useState('')
  const [attachments, setAttachments] = useState<Attachment[]>([])
  const [sendState, setSendState] = useState<'idle' | 'sending' | 'sent'>('idle')

  // Reset state when modal opens with fresh data
  useEffect(() => {
    if (isOpen) {
      setSubject(`Report: ${reportName}`)
      setBody(
        `Hi,\n\nPlease find the report "${reportName}" generated from ${dataSource?.name ?? 'your data'}.\n\nAttachments:\n` +
        charts.map(c => `  • ${c.title} (${c.type})`).join('\n') +
        '\n\nGenerated by Rsend.'
      )
      setAttachments(buildAttachments(charts, dataSource))
      setSendState('idle')
    }
  }, [isOpen, reportName, dataSource, charts])

  if (!isOpen) return null

  function toggle(id: string) {
    setAttachments(prev =>
      prev.map(a => (a.id === id ? { ...a, checked: !a.checked } : a))
    )
  }

  function handleSend() {
    if (sendState !== 'idle') return
    setSendState('sending')
    setTimeout(() => {
      setSendState('sent')
      setTimeout(() => {
        setSendState('idle')
        onClose()
      }, 2200)
    }, 1800)
  }

  const selectedCount = attachments.filter(a => a.checked).length
  const canSend = sendState === 'idle' && selectedCount > 0 && subject.trim().length > 0

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-sm">
      <div className="bg-white rounded-2xl shadow-2xl w-full max-w-xl max-h-[90vh] overflow-hidden flex flex-col">

        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-slate-100 shrink-0">
          <div className="flex items-center gap-3">
            <div className="w-9 h-9 rounded-xl bg-indigo-50 flex items-center justify-center">
              <Mail size={17} className="text-indigo-600" />
            </div>
            <div>
              <h2 className="font-semibold text-slate-800 text-sm">Send Report by Email</h2>
              <p className="text-xs text-slate-400">Choose what to include and compose your message</p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-2 text-slate-400 hover:text-slate-700 hover:bg-slate-100 rounded-lg transition-colors"
          >
            <X size={15} />
          </button>
        </div>

        {/* Success state */}
        {sendState === 'sent' ? (
          <div className="flex flex-col items-center justify-center py-16 flex-1">
            <div className="w-16 h-16 rounded-full bg-emerald-100 flex items-center justify-center mb-4">
              <Check size={28} className="text-emerald-600" />
            </div>
            <p className="font-semibold text-slate-800">Email Sent!</p>
            <p className="text-sm text-slate-500 mt-1">Delivered to <span className="font-medium">{userEmail}</span></p>
          </div>
        ) : (
          <div className="flex-1 overflow-y-auto p-6 space-y-4 scrollbar-thin">

            {/* To */}
            <div>
              <label className="block text-xs font-semibold text-slate-500 uppercase tracking-wider mb-1.5">To</label>
              <input
                value={userEmail}
                readOnly
                className="w-full border border-slate-100 rounded-lg px-3 py-2 text-sm text-slate-500 bg-slate-50 cursor-not-allowed"
              />
            </div>

            {/* Subject */}
            <div>
              <label className="block text-xs font-semibold text-slate-500 uppercase tracking-wider mb-1.5">Subject</label>
              <input
                value={subject}
                onChange={e => setSubject(e.target.value)}
                className="w-full border border-slate-200 rounded-lg px-3 py-2 text-sm text-slate-700 focus:outline-none focus:ring-2 focus:ring-indigo-400"
              />
            </div>

            {/* Body */}
            <div>
              <label className="block text-xs font-semibold text-slate-500 uppercase tracking-wider mb-1.5">Message Body</label>
              <textarea
                value={body}
                onChange={e => setBody(e.target.value)}
                rows={5}
                className="w-full border border-slate-200 rounded-lg px-3 py-2 text-sm text-slate-700 focus:outline-none focus:ring-2 focus:ring-indigo-400 resize-none"
              />
            </div>

            {/* Attachments */}
            <div>
              <div className="flex items-center gap-1.5 mb-2">
                <Paperclip size={12} className="text-slate-400" />
                <label className="text-xs font-semibold text-slate-500 uppercase tracking-wider">
                  Select Attachments
                </label>
              </div>

              {attachments.length === 0 ? (
                <p className="text-xs text-slate-400 py-2">No visualizations generated yet.</p>
              ) : (
                <div className="space-y-2">
                  {attachments.map(att => {
                    const meta = kindMeta[att.kind]
                    return (
                      <label
                        key={att.id}
                        className={`flex items-center gap-3 p-3 rounded-xl border cursor-pointer select-none transition-colors ${
                          att.checked
                            ? 'border-indigo-200 bg-indigo-50/60'
                            : 'border-slate-100 bg-white hover:bg-slate-50'
                        }`}
                      >
                        <input
                          type="checkbox"
                          checked={att.checked}
                          onChange={() => toggle(att.id)}
                          className="rounded accent-indigo-600 shrink-0"
                        />
                        <span className={`p-1.5 rounded-lg shrink-0 ${meta.iconClass}`}>
                          {meta.icon}
                        </span>
                        <div className="flex-1 min-w-0">
                          <p className="text-sm font-medium text-slate-700 truncate">{att.label}</p>
                          <p className="text-xs text-slate-400">{att.sublabel}</p>
                        </div>
                        <span className={`text-xs px-2 py-0.5 rounded-full font-semibold shrink-0 ${meta.badgeClass}`}>
                          {meta.badge}
                        </span>
                      </label>
                    )
                  })}
                </div>
              )}
            </div>

            {/* Summary pill */}
            {selectedCount > 0 && (
              <div className="flex items-center gap-2 px-3 py-2 bg-slate-50 rounded-lg text-xs text-slate-500">
                <Check size={12} className="text-emerald-500" />
                <span>
                  {selectedCount} attachment{selectedCount !== 1 ? 's' : ''} selected — sending to{' '}
                  <span className="font-medium text-slate-700">{userEmail}</span>
                </span>
              </div>
            )}
          </div>
        )}

        {/* Footer */}
        {sendState !== 'sent' && (
          <div className="flex items-center justify-end gap-3 px-6 py-4 border-t border-slate-100 shrink-0">
            <button
              onClick={onClose}
              className="px-4 py-2 text-sm font-medium text-slate-600 hover:bg-slate-100 rounded-lg transition-colors"
            >
              Cancel
            </button>
            <button
              onClick={handleSend}
              disabled={!canSend}
              className="flex items-center gap-2 px-5 py-2.5 bg-indigo-600 hover:bg-indigo-700 disabled:opacity-50 disabled:cursor-not-allowed text-white text-sm font-semibold rounded-lg transition-colors"
            >
              {sendState === 'sending' ? (
                <>
                  <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                  Sending…
                </>
              ) : (
                <>
                  <Send size={14} />
                  Send Report
                </>
              )}
            </button>
          </div>
        )}
      </div>
    </div>
  )
}
